<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Version>$(VersionPrefix).$(VersionSuffix)</Version>
        <TargetFrameworks>net45;net6.0-windows;net8.0-windows;net10.0-windows</TargetFrameworks>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>../../MetroFramework.snk</AssemblyOriginatorKeyFile>
        <PackageId>$(MSBuildProjectName)</PackageId>
        <PackageOutputPath>$(SolutionDir)Packages\</PackageOutputPath>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <RepositoryUrl>https://github.com/thielj/MetroFramework/MetroFramework.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <None Include="Resources\Open Sans License.txt" />
        <EmbeddedResource Include="Resources\Open_Sans_Bold.ttf" />
        <EmbeddedResource Include="Resources\Open_Sans_Light.ttf" />
        <EmbeddedResource Include="Resources\Open_Sans.ttf" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.Bitbucket.Git" IncludeAssets="runtime; build; native; contentfiles; analyzers" PrivateAssets="all" Version="8.0.0" />
        <PackageReference Include="Net4x.NuGetUtility" PrivateAssets="All" Version="$(NuGetUtilityVersion)" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\MetroFramework.Library\MetroFramework.Library.csproj" />
    </ItemGroup>
    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="README.md" Link="README.md" Pack="true" PackagePath="\README.md" />
    </ItemGroup>
</Project>